#!/usr/bin/env bash
# Configure domain zone so that the subdomain www points to load-balancer IP

func () {
	dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" |awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to "$5 }'
}

if [ "$#" -eq 2 ]
then
	func "$2.$1" "$2"
else
	func "www.$1" 'www'
	func "lb-01.$1" 'lb-01'
	func "web-01.$1" 'web-01'
	func "web-02.$1" 'func "web-02'
fi
