#!/usr/bin/env bash

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom404.html
sudo sed -i '/listen 80 default_server/a error_page 404 /custom404.html;' /etc/nginx/sites-available/default
sudo servie nginx restart
