#!/usr/bin/env bash
# make previous fix short and sweet here
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo pkill -o nginx
